language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      lsb_release -a;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main';
      sudo apt-get update;
      if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-5 g++-5; sudo update-alternatives --remove-all gcc; sudo update-alternatives --remove-all g++; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50; sudo update-alternatives --install /usr/bin/gcc g++ /usr/bin/g++-5 50; sudo update-alternatives --config gcc; sudo update-alternatives --config g++; fi;
      if [ "$CC" = "clang" ]; then sudo apt-get install clang-3.6; fi;
      sudo apt-get install -y libmysqlclient-dev;
      sudo apt-get install -y libmicrohttpd-dev;
      sudo apt-get install -y libssl-dev;
      sudo apt-get install -y check lcov;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew install check lcov;
    fi
  - gem install coveralls-lcov
  - cd $TRAVIS_BUILD_DIR/deps/mruby
  - ./minirake
  - cd $TRAVIS_BUILD_DIR

script:
  - $CC --version
  - sh autogen.sh
  - ./configure --with-gcov --enable-debug
  - make
  - make check

after_success:
  - if [ $CC = clang ]; then
      lcov --compat-libtool --directory . --capture --output-file coverage.info;
      sed -i.bak 's/ofpsvr\/test\/test/ofpsvr\/test/g' coverage.info;
      coveralls-lcov coverage.info;
    fi
  - if [ $CC = gcc ]; then
      cd $TRAVIS_BUILD_DIR;
      make distclean;
      export OFPSVR_NIGHT=$(date "+%Y-%m-%d").$(git rev-parse --short HEAD);
      mkdir $TRAVIS_BUILD_DIR/tmp;
      echo $TRAVIS_BUILD_DIR/tmp/$OFPSVR_NIGHT;
      mkdir $TRAVIS_BUILD_DIR/tmp/$OFPSVR_NIGHT;
      ./configure --prefix=$TRAVIS_BUILD_DIR/tmp/$OFPSVR_NIGHT;
      make;
      make check;
      make install;
      cd $TRAVIS_BUILD_DIR/tmp;
      mkdir nightly;
      tar czf nightly/$OFPSVR_NIGHT.tar.gz $OFPSVR_NIGHT;
      cd $TRAVIS_BUILD_DIR;
      ./scripts/deploy;
    fi