language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install -y gcc-5;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50;
      sudo apt-get install -y libmysqlclient-dev;
      sudo apt-get install -y libmicrohttpd-dev;
      sudo apt-get install -y libssl-dev;
      sudo apt-get install -y check lcov;
      echo $CXX;
      echo $CXX;
      echo $CXX;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew install check lcov;
    fi
  - gem install coveralls-lcov
  - cd $TRAVIS_BUILD_DIR/deps/mruby
  - ./minirake
  - cd $TRAVIS_BUILD_DIR

script:
  - sh autogen.sh
  - ./configure --with-gcov
  - make
  - make check

after_success:
  - if [ $CC = clang ]; then
      lcov --compat-libtool --directory . --capture --output-file coverage.info;
      sed -i.bak 's/ofpsvr\/test\/test/ofpsvr\/test/g' coverage.info;
      coveralls-lcov coverage.info;
    fi
