language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      lsb_release -a;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main';
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      sudo apt-get update;
      if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-5 g++-5; sudo update-alternatives --remove-all gcc; sudo update-alternatives --remove-all g++; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; sudo update-alternatives --config gcc; sudo update-alternatives --config g++; fi;
      if [ "$CC" = "clang" ]; then sudo apt-get install --allow-unauthenticated llvm-3.6 llvm-3.6-dev clang-3.6 libstdc++-4.9-dev; export CXX="clang++-3.6" CC="clang-3.6"; fi;
      sudo apt-get install -y libmysqlclient-dev;
      sudo apt-get install -y libmicrohttpd-dev;
      sudo apt-get install -y libssl-dev;
      sudo apt-get install -y check lcov;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew install check lcov;
    fi
  - gem install coveralls-lcov
  - cd /tmp
  - wget http://ftp.gnu.org/gnu/automake/automake-1.14.tar.gz
  - tar xzf automake-1.14.tar.gz
  - cd automake-1.14
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - $CC --version
  - aclocal --version
  - autoconf --version
  - automake --version
  - sh autogen.sh
  - ./configure --with-gcov --enable-debug
  - make
  - make check

after_success:
  - if [ $CC = "clang-3.6" ]; then
      lcov --compat-libtool --directory . --capture --output-file coverage.info;
      sed -i.bak 's/ofpsvr\/test\/test/ofpsvr\/test/g' coverage.info;
      coveralls-lcov coverage.info;
    fi
